import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { CLIENT_ROOT } from "../../server/config.js";
import { ensureIdeProjectSettings } from "../../server/idePlugins/index.js";
import { resolveWorkspaceRoot } from "./manifest.mjs";

export async function ensureWebProjectIdeSetup(projectPath, sdkRootOverride) {
  try {
    const sdkRoot = sdkRootOverride ?? resolveWorkspaceRoot(process.env, CLIENT_ROOT);
    const sdkTsconfig = path.join(sdkRoot, "tsconfig.game.json");
    if (!existsSync(sdkTsconfig)) return false;
    const extendsPath = path.resolve(sdkTsconfig).split(path.sep).join("/");
    const contents = `{
  // Generated by the editor for IDE tooling — machine-local; exclude from version control.
  "extends": "${extendsPath}",
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
`;
    const target = path.join(projectPath, "tsconfig.json");
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    let changed = false;
    if (existing !== contents) {
      await fs.writeFile(target, contents);
      changed = true;
    }

    // Flag use of unstable engine internals: game code should import from the
    // stable @engine/sdk/v1/* API. Raw @engine/* still works (warn, not error) but
    // may change without a version bump. See apps/web/src/engine/sdk/v1/README.md.
    const oxlintContents = `${JSON.stringify(
      {
        rules: {
          "no-restricted-imports": [
            "warn",
            {
              patterns: [
                {
                  group: ["@engine/**", "!@engine/sdk/v1/**"],
                  message:
                    "Use the stable @engine/sdk/v1/* API. Raw @engine/* modules are internal and may change without a version bump.",
                },
              ],
            },
          ],
        },
      },
      null,
      2,
    )}\n`;
    const oxlintTarget = path.join(projectPath, ".oxlintrc.json");
    const existingOxlint = await fs.readFile(oxlintTarget, "utf8").catch(() => null);
    if (existingOxlint !== oxlintContents) {
      await fs.writeFile(oxlintTarget, oxlintContents);
      changed = true;
    }

    const typescriptLibCandidates = [
      path.join(sdkRoot, "node_modules", "typescript", "lib"),
      path.join(sdkRoot, "pkg", "node_modules", "typescript", "lib"),
    ];
    const typescriptLib = typescriptLibCandidates.find((candidate) => existsSync(candidate));
    if (typescriptLib) {
      changed = (await ensureIdeProjectSettings(projectPath, typescriptLib)) || changed;
    }
    return changed;
  } catch {
    return false;
  }
}
