import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { CLIENT_ROOT } from "../../server/config.js";
import { ensureIdeProjectSettings } from "../../server/idePlugins/index.js";
import { resolveWorkspaceRoot } from "./manifest.mjs";

export async function ensureWebProjectIdeSetup(projectPath, sdkRootOverride) {
  try {
    const sdkRoot = sdkRootOverride ?? resolveWorkspaceRoot(process.env, CLIENT_ROOT);
    const sdkTsconfig = path.join(sdkRoot, "tsconfig.game.json");
    if (!existsSync(sdkTsconfig)) return false;
    const extendsPath = path.resolve(sdkTsconfig).split(path.sep).join("/");
    const contents = `{
  // Generated by the editor for IDE tooling — machine-local; exclude from version control.
  "extends": "${extendsPath}",
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
`;
    const target = path.join(projectPath, "tsconfig.json");
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    let changed = false;
    if (existing !== contents) {
      await fs.writeFile(target, contents);
      changed = true;
    }

    const typescriptLibCandidates = [
      path.join(sdkRoot, "node_modules", "typescript", "lib"),
      path.join(sdkRoot, "pkg", "node_modules", "typescript", "lib"),
    ];
    const typescriptLib = typescriptLibCandidates.find((candidate) => existsSync(candidate));
    if (typescriptLib) {
      changed = (await ensureIdeProjectSettings(projectPath, typescriptLib)) || changed;
    }
    return changed;
  } catch {
    return false;
  }
}
