import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { CLIENT_ROOT } from "../../server/config.js";
import {
  collectIdeGitignoreEntries,
  ensureIdeProjectSettings,
} from "../../server/idePlugins/index.js";
import { resolveWorkspaceRoot } from "./manifest.mjs";

async function ensureDevGitignore(projectPath) {
  const target = path.join(projectPath, ".gitignore");
  const existing = await fs.readFile(target, "utf8").catch(() => "");
  const missing = collectIdeGitignoreEntries().filter(
    (entry) => !existing.split(/\r?\n/).includes(entry),
  );
  if (missing.length === 0) return false;
  const prefix = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
  const block = `${prefix}\n# Machine-local IDE files generated by Blackbox Editor\n${missing.join("\n")}\n`;
  await fs.writeFile(target, existing + block);
  return true;
}

export async function ensureWebProjectIdeSetup(projectPath, sdkRootOverride) {
  try {
    const sdkRoot = sdkRootOverride ?? resolveWorkspaceRoot(process.env, CLIENT_ROOT);
    const sdkTsconfig = path.join(sdkRoot, "tsconfig.game.json");
    if (!existsSync(sdkTsconfig)) return false;
    const extendsPath = path.resolve(sdkTsconfig).split(path.sep).join("/");
    const contents = `{
  // Generated by the editor for IDE tooling — do not commit. See .gitignore.
  "extends": "${extendsPath}",
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
`;
    const target = path.join(projectPath, "tsconfig.json");
    const existing = await fs.readFile(target, "utf8").catch(() => null);
    let changed = false;
    if (existing !== contents) {
      await fs.writeFile(target, contents);
      changed = true;
    }

    const typescriptLibCandidates = [
      path.join(sdkRoot, "node_modules", "typescript", "lib"),
      path.join(sdkRoot, "pkg", "node_modules", "typescript", "lib"),
    ];
    const typescriptLib = typescriptLibCandidates.find((candidate) => existsSync(candidate));
    if (typescriptLib) {
      changed = (await ensureIdeProjectSettings(projectPath, typescriptLib)) || changed;
    }
    changed = (await ensureDevGitignore(projectPath)) || changed;
    return changed;
  } catch {
    return false;
  }
}
