export {
  API_VERSION,
  API_PREFIX,
  API_PREFIX as API_BASE,
  Api,
  GlobalRoutes,
  ProjectRoutes,
  globalApiUrl,
  projectApiUrl,
  projectMediaUrl,
  projectToolsRunUrl,
  projectBuildRunCancelUrl,
  serverProjectRoute,
  serverProjectMediaRoute,
  serverToolsRunRoute,
  serverBuildRunCancelRoute,
} from "../../shared/apiPaths.js";
